"""Initial Setup

Revision ID: 6b2a960f56b4
Revises: 
Create Date: 2025-06-30 09:21:07.918185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2a960f56b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('cn', sa.String(length=255), nullable=True),
    sa.Column('requester_ip', sa.String(length=45), nullable=True),
    sa.Column('requester_user_agent', sa.Text(), nullable=True),
    sa.Column('cert_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ovpn_content', sa.LargeBinary(), nullable=True),
    sa.Column('downloadable', sa.Boolean(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_tokens_cn'), ['cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_download_tokens_user'), ['user'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_tokens_user'))
        batch_op.drop_index(batch_op.f('ix_download_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_download_tokens_cn'))

    op.drop_table('download_tokens')
    # ### end Alembic commands ###
