"""Add optionset to download_token table

Revision ID: 6dbffa595e1c
Revises: 8342a9532241
Create Date: 2025-07-02 09:07:09.969910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbffa595e1c'
down_revision = '8342a9532241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optionset_used', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_column('optionset_used')

    # ### end Alembic commands ###
