"""Added OS detection via user agent to download_token table

Revision ID: 8342a9532241
Revises: 6b2a960f56b4
Create Date: 2025-06-30 09:54:27.459968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8342a9532241'
down_revision = '6b2a960f56b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent_string', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('detected_os', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_column('detected_os')
        batch_op.drop_column('user_agent_string')

    # ### end Alembic commands ###
