{{- if .Values.optionsets.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if .Values.optionsets.configMap }}{{ .Values.optionsets.configMap }}{{ else }}{{ include "ovpn-manager.fullname" . }}{{ .Values.optionsets.configMapSuffix }}{{ end }}
  labels:
    {{- include "ovpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- range $filename, $content := .Values.optionsets.files }}
  {{ $filename | quote }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end -}}