apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ovpn-manager.fullname" . }}
  labels:
    {{- include "ovpn-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ovpn-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ovpn-manager.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: GUNICORN_LOGLEVEL
              value: {{ .Values.gunicorn.logLevel | quote }}
            - name: OVPN_TEMPLATES_PATH
              value: {{ .Values.templates.mountPath | quote }}
            - name: OVPN_OPTIONSETS_PATH
              value: {{ .Values.optionsets.mountPath | quote }}
            - name: FLASK_APP
              value: "server.app"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef: 
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom: 
                secretKeyRef: 
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: OIDC_DISCOVERY_URL
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: FLASK_SECRET_KEY
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: ENCRYPTION_KEY
            - name: OIDC_ADMIN_GROUP
              valueFrom:
                secretKeyRef:
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: OIDC_ADMIN_GROUP
            - name: CA_CERT_PATH
              value: /etc/ca/ca.crt
            - name: CA_KEY_PATH
              value: /etc/ca/ca.key
            {{- if or .Values.database.path (and .Values.database.type .Values.database.username .Values.database.password .Values.database.hostname .Values.database.database) }}
            - name: DATABASE_URL
              valueFrom: 
                secretKeyRef:
                  name: {{ include "ovpn-manager.fullname" . }}
                  key: DATABASE_URL
            {{- end }}
          volumeMounts:
            - name: ca-volume
              mountPath: "/etc/ca"
              readOnly: true
            - name: tmp-volume
              mountPath: "/tmp"
            - name: instance-volume
              mountPath: "/usr/src/app/instance"
            - name: ovpn-templates-volume
              mountPath: {{ .Values.templates.mountPath }}
              readOnly: true
            - name: ovpn-optionsets-volume
              mountPath: {{ .Values.optionsets.mountPath }}
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30 # Wait 30 seconds before the first check
            periodSeconds: 20       # Check every 20 seconds
            timeoutSeconds: 5         # Allow up to 5 seconds for a response
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15 # Wait 15 seconds before the first check
            periodSeconds: 10       # Check every 10 seconds
            timeoutSeconds: 5         # Allow up to 5 seconds for a response
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ovpn-templates-volume
          configMap:
            name: {{ if .Values.templates.configMap }}{{ .Values.templates.configMap }}{{ else }}{{ include "ovpn-manager.fullname" . }}{{ .Values.templates.configMapSuffix }}{{ end }}
        - name: ovpn-optionsets-volume
          configMap:
            name: {{ if .Values.optionsets.configMap }}{{ .Values.optionsets.configMap }}{{ else }}{{ include "ovpn-manager.fullname" . }}{{ .Values.optionsets.configMapSuffix }}{{ end }}
        - name: ca-volume
          secret:
            secretName: {{ include "ovpn-manager.fullname" . }}
            items:
            - key: ca.crt
              path: ca.crt
            - key: ca.key
              path: ca.key
        - name: tmp-volume
          emptyDir: {}
        - name: instance-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}