{{- define "connection" -}}
{{- if and .Values.database.protocol .Values.database.username .Values.database.password .Values.database.hostname .Values.database.database -}}
{{ .Values.database.protocol }}://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.hostname }}{{ if .Values.database.port }}:{{ .Values.database.port }}{{ end }}/{{ .Values.database.database }}
{{- else if .Values.database.path -}}
sqlite://{{ .Values.database.path }}
{{- end -}}
{{- end -}}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovpn-manager.fullname" . }}
  labels:
    {{- include "ovpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  FLASK_SECRET_KEY: {{ .Values.secrets.flaskSecretKey | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.secrets.oidc.clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidc.clientSecret | b64enc | quote }}
  OIDC_DISCOVERY_URL: {{ .Values.secrets.oidc.discoveryUrl | b64enc | quote }}
  {{- if .Values.secrets.ca.key }}
  ca.key: {{ .Values.secrets.ca.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ca.crt }}
  ca.crt: {{ .Values.secrets.ca.crt | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.tlscrypt.key }}
  tlscrypt.key: {{ .Values.secrets.tlscrypt.key | b64enc | quote }}
  {{- end }}
  DATABASE_URL: {{ include "connection" . | b64enc | quote }}
  OIDC_ADMIN_GROUP: {{ .Values.oidc_admin_group | b64enc | quote }}
{{- end }}